#!/usr/bin/env node
'use strict';

var traceur = require('traceur');

traceur.require.makeDefault(function(filename) {
  return filename.indexOf('node_modules') === -1;
}, {
  generators: 'parse'
});

require('./lib/console');
